title: 박태현
description: Data Analyst
site_title: '@abhn - TpthsunL'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: abhn
blog_url: https://www.nagekar.com
email: psps4755@naver.com 
keybase_username: abhn
twitter_username: abhn_
reddit_username: abhn

# absolute or relative
profile_picture: assets/images/pk.jpg

# Google Analytics ID
google_analytics: 
